name: workshop-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - pip
  - pip:
    - tensorflow
    - keras
    - scikit-learn